### ISSUE TITLE
false precision in bins?

### ISSUE THREAD

**Issue by afontenot** [tomcm39/COVID19_expert_survey#1]
Hi, I'm not really qualified to comment on your research, so feel free to just close this issue if responding will waste your time.

I was looking through the CSV of your data and found it peculiar that instead of calculating a probability for each bin independently according to your model, you seem to have used control points, and interpolated linearly between them. (This for the only subset of data I looked at, QF4 from 2020-03-30.)

The probably curve has long stretches of constant slope for some multiple of 10 bins, which is quite a lot of the probability space at the low end:

![model](https://user-images.githubusercontent.com/3870410/78509987-e3b61b00-7746-11ea-8e4c-af2f95ddfcb9.png)

I wonder if there are limits on your model that prevent determining a probability for every point, and whether this might lead to issues in determining reasonable probability ranges (e.g. a 5% - 95% range of possibilities). In particular, the median point you reported in your [latest summary](https://works.bepress.com/mcandrew/4/download/), 262500, falls in the middle of a constant-slope segment of *100 bins* (50k deaths). 

(The results are not always constant over exactly some multiple of 10 bins; to be more precise, they looks like results I've gotten when trying to interpolate splines over a bunch of control points. There's sometimes a little bit of flex right around the knots or a slight change in slope partway between two points.)

**Comment by tomcm39** [comment]
Hi afontenot,

Thank you for the thoughtful question, and for checking in on my work!
For the consensus probability distribution you plotted above, I binned the horizontal axis. 
The question related to the number of deaths by the end of 2020 you potted above is from the survey issued on 2020-03-30 and was question number 4. For this question I used bins of size 500 (i.e. 0-500 deaths, 501-1000 and so on).

I can recompute the consensus distribution for all the questions for bins of size 1 (a single death) but I don't think models can really compute probabilities on a national scale at that resolution. 

Please let me know if that answers your question.
best
tom
